### ISSUE TITLE
The Input file *.csv format in the README.md

### ISSUE THREAD

**Issue by yumzhang17** [Pappulab/FIREBALL#2]
Hi there,

The FIREBALL tutorial is clean and easy to follow! :D I have used FIREBALL, which successfully fits the phase diagram for my systems. 

While I was using the tutorial, I found that the example of "Input files" (Temp, Dense, Dilute, Dense_Error, Dilute_Error), say the *.csv file, may have a small typo/bug? The last comma each line will make the tutorial not correctly executed? 

i.e., input_file end without comma each data line like below will work:
'''
Temp, Dense, Dilute, Dense_Error, Dilute_Error
277.15, , 0.169, , 0.003
278.15, 393, 0.177, , 0.004
279.15, , 0.207, , 0.004
281.15, , 0.304, , 0.004
'''

Or maybe my environment is slightly incompatible with the code? 
Thank you again for this powerful tool!

**Comment by jaredl7** [comment]
Thanks for catching that, @yumzhang17! With the trailing comma, `fireball-fit` does indeed crash when analyzing any such file. From what I can gather, the trailing commas in the CSV excerpt quoted in the README.md are an artifact from an Excel conversion. I've removed those and the changes are reflected in the latest version. Thanks so much again!
